#echo 'direct weak @2.42'
#python baselines.py rf_direct_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt split

#echo 'direct strong @2.31'
#python baselines.py rf_direct_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt split

#echo 'street_split weak @2.44'
#python baselines.py rf_street_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt split

#echo 'street split strong @2.38'
#python baselines.py rf_street_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt split

#echo 'street split fold_0 to test @2.37'
#python baselines.py rf_street_split /features/redo_fold_0_pool.csv /features/test_pool.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt sub

#echo 'street split fold_1 to test @2.37'
#python baselines.py rf_street_split /features/redo_fold_1_pool.csv /features/test_pool.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt sub

echo 'street split lr 2.639'
python baselines.py rf_street_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category lr 'solver:s:lbfgs multi_class:s:multinomial verbose:i:1 C:f:0.01 n_jobs:i:10' ./pred split_test.txt split

echo 'street split lr 2.636'
python baselines.py rf_street_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category lr 'solver:s:lbfgs multi_class:s:multinomial verbose:i:1 C:f:0.01 n_jobs:i:10' ./pred split_test.txt split

#echo 'street split without address weak @2.47'
#python baselines.py rf_street_split /0_direct/train.csv /0_direct/test.csv /features/redo_fold_0_pool.csv /features/redo_fold_1_pool.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,X,Y,street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred split_test.txt split




