# 2.42
#python baselines.py rf_direct_all /0_direct/train.csv /0_direct/test.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# weak model tests

# 2.45
#python baselines.py rf_no_street /0_direct/train.csv /0_direct/test.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.31
#python baselines.py rf_street /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38,Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.27
#python baselines.py rf_points /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,points_0,points_1,points_2,points_3,points_4,points_5,points_6,points_7,points_8,points_9,points_10,points_11,points_12,points_13,points_14,points_15,points_16,points_17,points_18,points_19,points_20,points_21,points_22,points_23,points_24,points_25,points_26,points_27,points_28,points_29,points_30,points_31,points_32,points_33,points_34,points_35,points_36,points_37,points_38' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.33
#python baselines.py rf_street /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38,Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

#python baselines.py rf_points /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'points_0,points_1,points_2,points_3,points_4,points_5,points_6,points_7,points_8,points_9,points_10,points_11,points_12,points_13,points_14,points_15,points_16,points_17,points_18,points_19,points_20,points_21,points_22,points_23,points_24,points_25,points_26,points_27,points_28,points_29,points_30,points_31,points_32,points_33,points_34,points_35,points_36,points_37,points_38,Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 1.82 sub 2.37
#python baselines.py rf_street /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38,Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 1.81
#python baselines.py rf_street /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'street_odds_0,street_odds_1,street_odds_2,street_odds_3,street_odds_4,street_odds_5,street_odds_6,street_odds_7,street_odds_8,street_odds_9,street_odds_10,street_odds_11,street_odds_12,street_odds_13,street_odds_14,street_odds_15,street_odds_16,street_odds_17,street_odds_18,street_odds_19,street_odds_20,street_odds_21,street_odds_22,street_odds_23,street_odds_24,street_odds_25,street_odds_26,street_odds_27,street_odds_28,street_odds_29,street_odds_30,street_odds_31,street_odds_32,street_odds_33,street_odds_34,street_odds_35,street_odds_36,street_odds_37,street_odds_38,Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,X,Y' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.03 sub 2.49
#python baselines.py rf_points /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,points_0,points_1,points_2,points_3,points_4,points_5,points_6,points_7,points_8,points_9,points_10,points_11,points_12,points_13,points_14,points_15,points_16,points_17,points_18,points_19,points_20,points_21,points_22,points_23,points_24,points_25,points_26,points_27,points_28,points_29,points_30,points_31,points_32,points_33,points_34,points_35,points_36,points_37,points_38' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.289 sub 2.30
python baselines.py rf_points /features/train_pool.csv /features/test_pool.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y' Category rf 'n_estimators:i:300 max_depth:i:15 min_samples_leaf:i:30 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv

# 2.41
#python baselines.py rf_oldstreet /3_refine_street/train.csv /3_refine_street/test.csv /0_direct/fold_0.csv /0_direct/fold_1.csv 'Year,Month,Day,Hour,Minute,Second,DayOfWeek,PdDistrict,Address1,Address2,X,Y,street_proba_0,street_proba_1,street_proba_2,street_proba_3,street_proba_4,street_proba_5,street_proba_6,street_proba_7,street_proba_8,street_proba_9,street_proba_10,street_proba_11,street_proba_12,street_proba_13,street_proba_14,street_proba_15,street_proba_16,street_proba_17,street_proba_18,street_proba_19,street_proba_20,street_proba_21,street_proba_22,street_proba_23,street_proba_24,street_proba_25,street_proba_26,street_proba_27,street_proba_28,street_proba_29,street_proba_30,street_proba_31,street_proba_32,street_proba_33,street_proba_34,street_proba_35,street_proba_36,street_proba_37,street_proba_38' Category rf 'n_estimators:i:30 max_depth:i:8 min_samples_leaf:i:80 random_state:i:0 verbose:i:1 n_jobs:i:10' ./pred final.txt cv